name: Deploy Stories to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    uses: rowtype-yoga/purescript-yoga-stories/.github/workflows/deploy-stories.yml@v0.1.13
